name: ServerZipper
version: '${project.version}'
main: twenty.pye.serverzipper.ServerZipper
commands:
  zip:
    description: Zip a file by providing a path
    permission: zipper.zip
  zipserver:
    description: Zip the whole server
    permission: zipper.zip
  upload:
    description: Uplaod the provided file to filebin.net
    permission: zipper.upload